SELECT
  PCPRODUT.CODPROD,
  PCPRODUT.DESCRICAO,
  PCFORNEC.CODFORNEC,
  PCDEPTO.DESCRICAO DEPARTAMENTO,
  PCSECAO.DESCRICAO SECAO,
  SUM(( (NVL(PCEST.QTEST,
          0)) - NVL(PCEST.QTESTGER,
        0))) ESTOQUEIDEAL,
  SUM(( (NVL(PCEST.QTEST,
          0)) * NVL(PCEST.CUSTOCONT,
        0))) / DECODE(SUM(( (NVL(PCEST.QTEST,
            0)))),
    0,
    1,
    SUM(( (NVL(PCEST.QTEST,
            0))))) CUSTOCONT,
  SUM((( (NVL(PCEST.QTEST,
            0)) - NVL(PCEST.QTESTGER,
          0)) * NVL(PCEST.CUSTOCONT,
        0))) VLDIFER,
  SUM(( (NVL(PCEST.QTEST,
          0)))) ESTCONT,
  SUM((NVL(PCEST.QTESTGER,
        0))) ESTGER,
  SUM(( (NVL(PCEST.QTEST,
          0)) * NVL(PCEST.CUSTOCONT,
        0))) Total,
  SUM((NVL(PCEST.QTESTGER,
        0) * NVL(PCEST.CUSTOCONT,
        0))) Total2,
  SUM(NVL(PCEST.QTRESERV,
      0)) QTRESERV
FROM
  PCEST,
  PCPRODUT,
  PCDEPTO,
  PCSECAO,
  PCFORNEC
WHERE
  ( PCPRODUT.CODPROD = PCEST.CODPROD)
  AND ((PCPRODUT.CODFILIAL = PCEST.CODFILIAL)
    OR (PCPRODUT.CODFILIAL = '99')
    OR (PCPRODUT.CODFILIAL IS NULL))
  AND PCEST.CODFILIAL = :CODFILIAL
  AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
  AND PCPRODUT.CODSEC = PCSECAO.CODSEC
  AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
  AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
  AND ((PCDEPTO.TIPOMERC NOT IN ('IM'))
    OR (PCDEPTO.TIPOMERC IS NULL))
  AND ((PCDEPTO.TIPOMERC NOT IN ('CI'))
    OR (PCDEPTO.TIPOMERC IS NULL))
GROUP BY
  PCPRODUT.CODPROD,
  PCPRODUT.DESCRICAO,
  PCPRODUT.EMBALAGEM,
  PCPRODUT.CODEPTO,
  PCPRODUT.CODSEC,
  PCFORNEC.CODFORNEC,
  PCFORNEC.FORNECEDOR,
  PCPRODUT.QTUNITCX,
  PCEST.QTRESERV,
  ((NVL(PCEST.QTESTGER,
        0)- (NVL(PCEST.QTEST,
          0) ) )*NVL(PCEST.CUSTOCONT,
      0)),
  PCDEPTO.DESCRICAO,
  PCSECAO.DESCRICAO
ORDER BY
  ESTOQUEIDEAL
